FROM wordpress:latest

RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN docker-php-ext-install pdo_mysql

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar\
    && chmod +x wp-cli.phar\
    && mv wp-cli.phar /usr/local/bin/wp

RUN usermod -u $UID www-data
RUN groupmod -o -g $GID www-data
